version: "3"

services:
    gotorrent:
        image: darknightlab/gotorrent:latest
        # build: .
        container_name: gotorrent
        restart: always
        network_mode: host
        volumes:
          - ./config:/app/config
          - ./cache:/app/cache
          - ./downloads:/app/downloads
    
    caddy:
        image: slothcroissant/caddy-cloudflaredns:latest
        container_name: gotorrent-web
        restart: always
        network_mode: host
        volumes:
          - ./caddy/Caddyfile:/etc/caddy/Caddyfile
          - ./caddy/data:/data
          - ./caddy/config:/config