Web:
    Port: 16102
    Address:
    Secret:
Engine:
    # 必须大于16384
    DownloadRateBurst: 209715200
    DownloadRateLimit: 104857600
    UploadRateBurst: 62914560
    UploadRateLimit: 41943040
    ListenPort: 16103
    UpnpID: # 默认为 "github.com/darknightlab/gotorrent (版本号)"
    ExtendedHandshakeClientVersion: # 默认为 "github.com/darknightlab/gotorrent (版本号)"
    Bep20: -qB4530- # 默认为 "-GTxxx0"
    DataDir: downloads
    Seed: true
    HTTPUserAgent: qBittorrent/4.5.3
    DisableIPv6: # false
    PublicIp4:
    PublicIp6:
Main:
    CacheDir: cache
    GotInfoTimeout: 60 # 0为不限制, 单位秒
    MaxSeedTime: 0 # 0为不限制, 单位秒
    SequentialDownload: false
    CachePrefix: __AUTOSAVED__
    DefaultTracker:
        - ["udp://tracker.opentrackr.org:1337/announce"]
        - ["https://tracker.lilithraws.org:443/announce"]
        - ["wss://tracker.kawaii.id"]
        - ["wss://tracker.btorrent.xyz"]
        - ["wss://tracker.openwebtorrent.com"]
